App_Account/urls.py
from django.urls import path
from App_Account.views import (
    SignupView, LoginView,activateView,DashboardView,LogoutView,PasswordChange,ProfileView,
    ProfileUpdateView,RentListView,AddRentView,RentEditView,RentDeleteView,PendingRentListView,
    PendingRentPreviewiew,ApprovePendingRentListView,CancelPendingRentListView,RentedListView,
    RentedListDetailsView,PurchaseListView,PurchaseDetailsView,PurchaseReportListView,ReportView,
    UserReportView,UserWiseReportView,ContactMessage,UserListView,UserActiveView
    )

app_name = 'App_Account'

urlpatterns = [
    path('signup/', SignupView, name='signup'),
    path('login/', LoginView, name='login'),
    path('logout',LogoutView,name='logout'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',activateView, name='activate'),
    path('password-change/',PasswordChange,name="passwordchange"),
    path('dashboard/',DashboardView,name='dashboard'),
    path('profile/',ProfileView,name='profile'),
    path('profileupdate/',ProfileUpdateView,name='profileupdate'),


    ################### House OWner Part #######################
    path('rent-list',RentListView,name='rentlist'),
    path('add-rent',AddRentView,name='addrent'),
    path('edit-rent/<int:id>',RentEditView,name='editrent'),
    path('delete-rent/<int:id>',RentDeleteView,name='rentdelete'),

    path('rented-list',RentedListView,name='rentedlist'),
    path('rented-details/<int:id>',RentedListDetailsView,name='renteddetails'),

    ################### Renter Part #######################
    path('pending-rent-list',PendingRentListView,name='pendingrentlist'),
    path('pending-rent-view/<int:id>',PendingRentPreviewiew,name='pendingrentpreview'),
    path('pending-rent-approved/<int:id>',ApprovePendingRentListView,name='approvependingrent'),
    path('pending-rent-cancel/<int:id>',CancelPendingRentListView,name='cancelpendingrent'),

    path('purchase-list',PurchaseListView,name='purchaselist'),
    path('purchase-details/<int:id>',PurchaseDetailsView,name='purchasedetails'),

    ################### Admin #######################
    path('purchase-report',PurchaseReportListView,name='purchasereport'),
    path('report-view',ReportView,name='reportview'),
    path('report-user',UserReportView,name='userreport'),
    path('report-user-view',UserWiseReportView,name='userwisereport'),
    path('contact',ContactMessage,name='contact'),
    path('userlists',UserListView,name='userlists'),
    path('user-active/<int:id>',UserActiveView,name='useractive'),
]

HouseRental/urls.py
from django.contrib import admin
from django.urls import path,include
from HouseRental.views import *
from HouseRental.views import page_not_found
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('post',RentPost,name='post'),
    path('contact',ContactView,name='contact'),
    path('faq',FaqView,name='faq'),
    path('about',AboutView,name='about'),
    path('details/<int:id>',Details,name="details"),
    path('checkout/<int:id>',create_checkout_session,name="checkout"),
    path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('reset-password/',
         PasswordResetView.as_view(template_name='App_Account/password_reset_form.html'), name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='App_Account/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='App_Account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='App_Account/password_reset_complete.html'),
         name='password_reset_complete'),
    path('account/',include('App_Account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# handler404 = page_not_found

templates/App_Dashboard/admindashboard.html
<div class="row g-3 my-2">
    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{housepost}}</h3>
                <p class="fs-5">Total Rent Post</p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{approved}}</h3>
                <p class="fs-5">Approved Post</p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{rejected}}</h3>
                <p class="fs-5">Reject Post</p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{saled}}</h3>
                <p class="fs-5">Total Rented</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{users}}</h3>
                <p class="fs-5">Total User</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{houseowner}}</h3>
                <p class="fs-5">Total HouseOwner</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{renter}}</h3>
                <p class="fs-5">Total Renter</p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="p-3 bg-white shadow-sm d-flex justify-content-around align-items-center rounded">
            <div>
                <h3 class="fs-2 text-center">{{totalreneted}}</h3>
                <p class="fs-5">Total Renter Amount</p>
            </div>
        </div>
    </div>
</div>
</div>

templates/App_Dashboard/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}EasyRent-Dashboard{% endblock%}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}">
    <link href="{% static 'alert/css/alert.css'%}" rel="stylesheet" />
    <link href="{% static 'alert/themes/default/theme.css'%}" rel="stylesheet" />

    {% block css%}

    {% endblock%}
</head>

<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-dark" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom">
                <a href="{% url 'home' %}">EasyRent</a>
            </div>
            <div class="list-group list-group-flush my-3">
                {% if request.user.is_superuser %}
                {% include 'App_Dashboard/superadminmenu.html'%}
                {% else %}
                {% include 'App_Dashboard/othermenu.html'%}
                {% endif%}
            </div>
        </div>

        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                    <!-- <h2 class="fs-2 m-0">Dashboard</h2> -->
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle second-text fw-bold" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user me-2"></i>{{request.user}}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'App_Account:logout'%}">Logout</a></li>
                                <li><a class="dropdown-item" href="{% url 'App_Account:passwordchange'%}">Change
                                        Password</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>

            {% block dashboard %}

            {% endblock%}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'alert/js/alert.js'%}"></script>
    <script>
        var el = document.getElementById("wrapper");
        var toggleButton = document.getElementById("menu-toggle");
        var sidebar = document.getElementById("sidebar-wrapper");
        var content = document.getElementById("page-content-wrapper");

        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
            sidebar.classList.toggle("hidesidebar");
            content.classList.toggle("fixedwidth");

        };
    </script>
    {% block js%}

    {% endblock%}
</body>

</html>

templates/App_Dashboard/contact.html
{% extends 'App_Dashboard/base.html'%}
{% load static%}
{% block dashboard%}
{% block css %}
<link href="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.css" rel="stylesheet">
<style>
    .dataTable {
        width: 100% !important;
    }
</style>
{% endblock %}
{% include 'alert.html'%}
<div class="container-fluid px-4">
    <div class="row my-5">
        <div class="col-lg-12 mb-2">
            <span class="mb-3" style="font-size: 24px;">Contact Us List
        </div>
        <hr>
        <div class="col">
            <table class="table bg-white rounded shadow-sm  table-hover" id="rentlist">
                <thead>
                    <tr>
                        <th scope="col" width="50">SL</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Created</th>
                        <th scope="col">Message</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in contacts %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{item.name}}</td>
                        <td>{{item.email}}</td>
                        <td>{{item.created}}</td>
                        <td>{{item.message}}</td>
                        <td>
                            <a target="_blank"
                                href="https://mail.google.com/mail/?view=cm&fs=1&to={{item.email}}&su=EasyRent Reply&body=Thanks for contact us."
                                class="btn btn-primary btn-sm">Reply</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}
{% block js%}
<script src="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#rentlist').DataTable();
        $(document).on('click', '.btnDelete', function (event) {
            event.preventDefault();
            var url = $(this).attr('href');

            $.alert.open('warning', 'Are you sure you want to delete this post?', function (confirmed) {
                if (confirmed) {
                    window.location.href = url;
                } else {
                    $.alert.open('info', 'Your post is safe!');
                }
            });
        })
    });
</script>
{% endblock%}

templates/App_Dashboard/dashboard.html
{% extends 'App_Dashboard/base.html'%}
{% load static%}
{% block dashboard%}
{% include 'alert.html'%}
{% if request.user.is_superuser %}
{% include 'App_Dashboard/admindashboard.html'%}
{% else %}
{% include 'App_Dashboard/otherdashboard.html'%}
{% endif%}
{% endblock %}

templates/App_Dashboard/otherdashboard.html
<div class="container-fluid px-4">
    <div class="row">
        <div class="col-lg-12">
            <div class="p-4">
                <div class="welcome text-center">
                    <div class="content rounded-3 p-3">
                        <h1 class="fs-3">Welcome to Dashboard</h1>
                        <p class="mb-0">Hello {{request.user}}, welcome to your awesome dashboard!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/App_Dashboard/profile.html
{% extends 'App_Dashboard/base.html'%}
{% load static%}
{% block dashboard%}
{% include 'alert.html'%}
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            {% if request.user.userprofile.photo %}
                            <img src="{{request.user.userprofile.photo.url}}" alt="profile" class="rounded-circle"
                                width="150">
                            {% else %}
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="profile"
                                class="rounded-circle" width="150">
                            {% endif %}

                            <div class="mt-3">
                                <h4>{{request.user}}</h4>
                                {% if request.user.is_superuser %}
                                <p class="text-secondary mb-1">Login as <b>Admin</b></p>
                                {% else %}
                                {% if request.user.userprofile %}
                                {% if request.user.userprofile.userType %}
                                <p class="text-secondary mb-1">Login as
                                    <b>{{request.user.userprofile.get_user_type }}</b>
                                </p>
                                {% endif %}
                                {% endif %}

                                {% endif%}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-4">
                                <h6 class="mb-0">Full Name</h6>
                            </div>
                            <div class="col-sm-8 text-secondary">
                                <b>:</b> {{ request.user.get_full_name }}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-8 text-secondary">
                                <b>:</b> {{request.user.email}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <h6 class="mb-0">Phone</h6>
                            </div>
                            <div class="col-sm-8 text-secondary">
                                <b>:</b> {{request.user.userprofile.mobile}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <h6 class="mb-0">Nid</h6>
                            </div>
                            <div class="col-sm-8 text-secondary">
                                <b>:</b> {{request.user.userprofile.nid}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <h6 class="mb-0">City</h6>
                            </div>
                            <div class="col-sm-8 text-secondary">
                                <b>:</b> {{request.user.userprofile.city}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <h6 class="mb-0">Present Address</h6>
                            </div>
                            <div class="col-sm-8 text-secondary">
                                <b>:</b> {{request.user.userprofile.present_address}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-4">
                                <h6 class="mb-0">Parmanent Address</h6>
                            </div>
                            <div class="col-sm-8 text-secondary">
                                <b>:</b> {{request.user.userprofile.permanent_address}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-12">
                                <a class="btn btn-info" href="{% url 'App_Account:profileupdate'%}">Update</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock%}

templates/App_Dashboard/profile_update.html
{% extends 'App_Dashboard/base.html'%}
{% load static%}
{% block css%}
<style>
    .update-container {
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }
</style>
{% endblock%}
{% block dashboard%}

<div class="container">
    <div class="row">
        <div class="col-lg-8 mx-auto update-container">
            <div class="main-body">
                <h3 class="text-left border-bottom mb-2">Update Profile</h2>
                    <form method="POST" class="row g-3" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="col-lg-6">
                            <label for="firstName" class="form-label">First Name</label>
                            <input type="text" class="form-control" id="firstName" name="firstName"
                                value="{{ request.user.first_name }}" required>
                        </div>
                        <div class="col-lg-6">
                            <label for="lastName" class="form-label">Last Name</label>
                            <input type="text" class="form-control" id="lastName" name="lastName"
                                value="{{ request.user.last_name }}" required>
                        </div>
                        <div class="col-lg-6">
                            <label for="mobile" class="form-label">Mobile</label>
                            <input type="text" class="form-control" id="mobile" name="mobile"
                                value="{{ request.user.userprofile.mobile }}" required>
                        </div>
                        <div class="col-lg-6">
                            <label for="nid" class="form-label">NID</label>
                            <input type="text" class="form-control" id="nid" name="nid"
                                value="{{ request.user.userprofile.nid }}" required>
                        </div>
                        <div class="col-lg-12">
                            <label for="presentAddress" class="form-label">Present Address</label>
                            <textarea class="form-control" id="presentAddress" name="presentAddress" rows="2"
                                required>{{ request.user.userprofile.present_address }}</textarea>
                        </div>
                        <div class="col-lg-12">
                            <label for="permanentAddress" class="form-label">Permanent Address</label>
                            <textarea class="form-control" id="permanentAddress" name="permanentAddress" rows="2"
                                required>{{ request.user.userprofile.permanent_address }}</textarea>
                        </div>
                        <div class="col-lg-6">
                            <label for="photo" class="form-label">Photo</label>
                            <input type="file" class="form-control" id="photo" name="photo" accept="image/*">
                        </div>
                        <div class="col-lg-6">
                            <label for="city" class="form-label">City</label>
                            <input type="text" class="form-control" id="city" name="city"
                                value="{{ request.user.userprofile.city }}" required>
                        </div>
                        <div class="col-lg-6">
                            <img id="imagePreview" src="#" alt="Preview"
                                style="display: none; max-width: 200px; max-height: 200px;">
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Update Profile</button>
                    </form>


            </div>
        </div>
    </div>

</div>

{% endblock%}
{% block js%}
<script>
    function handleFileInputChange(event) {
        const file = event.target.files[0];
        if (file && file.type.startsWith('image/')) {
            const reader = new FileReader();
            reader.onload = function (event) {
                const imagePreview = document.getElementById('imagePreview');
                imagePreview.src = event.target.result;
                imagePreview.style.display = 'block';
            };
            reader.readAsDataURL(file);
        }
    }
    const photoInput = document.getElementById('photo');
    photoInput.addEventListener('change', handleFileInputChange);
</script>
{% endblock%}

templates/App_Dashboard/rentedlist.html
{% extends 'App_Dashboard/base.html'%}
{% load static%}
{% block dashboard%}
{% block css %}
<link href="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.css" rel="stylesheet">
<style>
    .dataTable {
        width: 100% !important;
    }
</style>
{% endblock %}
{% include 'alert.html'%}
<div class="container-fluid px-4">
    <div class="row my-5">
        <div class="col-lg-12 mb-2">
            <span class="mb-3" style="font-size: 24px;">Rented List
        </div>
        <hr>


        <div class="col">
            <table class="table bg-white rounded shadow-sm  table-hover" id="rentlist">
                <thead>
                    <tr>
                        <th scope="col" width="50">SL</th>
                        <th scope="col">Post Title</th>
                        <th scope="col">Purchase By</th>
                        <th scope="col">Total Price</th>
                        <th scope="col">Paid Amount</th>
                        <th scope="col">Due Amount</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in myrent_list%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{item.post.title}}</td>
                        <td>{{item.user}}</td>
                        <td>{{item.post.monthly_rent}}</td>
                        <td>{{item.post.advacne_rent}}</td>
                        <td>{{item.due_amount}}</td>
                        <td>
                            {% if item.is_paid == True %}
                            <span class="badge bg-success text-light p-2">Paid</span>
                            {% else %}
                            <span class="badge bg-warning text-light p-2">cancel</span>
                            {% endif %}
                        </td>
                        <td>
                            <div class="d-flex align-items-center list-action">
                                <a class="badge bg-danger" href="{% url 'App_Account:renteddetails' item.id %}"><i
                                        class="fa fa-eye"></i></a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}
{% block js%}
<script src="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.js"></script>
<script>
</script>
{% endblock%}

templates/App_Dashboard/rentlist.html
{% extends 'App_Dashboard/base.html'%}
{% load static%}
{% block dashboard%}
{% block css %}
<link href="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.css" rel="stylesheet">
<style>
    .dataTable {
        width: 100% !important;
    }
</style>
{% endblock %}
{% include 'alert.html'%}
<div class="container-fluid px-4">
    <div class="row my-5">
        <div class="col-lg-12 mb-2">
            <span class="mb-3" style="font-size: 24px;">Rent List<a href="{% url 'App_Account:addrent'%}"
                    style="float: inline-end;" class="btn btn-primary">Add Rent Post</a>
        </div>
        <hr>


        <div class="col">
            <table class="table bg-white rounded shadow-sm  table-hover" id="rentlist">
                <thead>
                    <tr>
                        <th scope="col" width="50">SL</th>
                        <th scope="col">Rent Title</th>
                        <th scope="col">City</th>
                        <th scope="col">Advannce</th>
                        <th scope="col">Total Rent</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in myrent_list%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{item.title}}</td>
                        <td>{{item.city}}</td>
                        <td>{{item.advacne_rent}}</td>
                        <td>{{item.monthly_rent}}</td>
                        <td>
                            {% if item.is_active == True %}
                            <span class="badge bg-success text-light p-2">Approved</span>
                            {% else %}
                            {% if item.is_reject == True%}
                            <span class="badge bg-danger text-light p-2">Cancel</span>
                            {% else %}
                            <span class="badge bg-warning text-light p-2">Pending</span>
                            {% endif %}
                            {% endif %}
                        </td>
                        <td>
                            <div class="d-flex align-items-center list-action">

                                {% if item.is_active == False %}
                                <a class="badge bg-success mx-2" href="{% url 'App_Account:editrent' item.id %}"><i
                                        class="fas fa-edit"></i></a>
                                <a class="badge bg-danger btnDelete"
                                    href="{% url 'App_Account:rentdelete' item.id %}"><i class="fa fa-trash"></i></a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}
{% block js%}
<script src="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#rentlist').DataTable();
        $(document).on('click', '.btnDelete', function (event) {
            event.preventDefault();
            var url = $(this).attr('href');

            $.alert.open('warning', 'Are you sure you want to delete this post?', function (confirmed) {
                if (confirmed) {
                    window.location.href = url;
                } else {
                    $.alert.open('info', 'Your post is safe!');
                }
            });
        })
    });
</script>
{% endblock%}