App_Account/urls.py
from django.urls import path
from App_Account.views import (
    SignupView, LoginView,activateView,DashboardView,LogoutView,PasswordChange,ProfileView,
    ProfileUpdateView,RentListView,AddRentView,RentEditView,RentDeleteView,PendingRentListView,
    PendingRentPreviewiew,ApprovePendingRentListView,CancelPendingRentListView,RentedListView,
    RentedListDetailsView,PurchaseListView,PurchaseDetailsView,PurchaseReportListView,ReportView,
    UserReportView,UserWiseReportView,ContactMessage,UserListView,UserActiveView
    )

app_name = 'App_Account'

urlpatterns = [
    path('signup/', SignupView, name='signup'),
    path('login/', LoginView, name='login'),
    path('logout',LogoutView,name='logout'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',activateView, name='activate'),
    path('password-change/',PasswordChange,name="passwordchange"),
    path('dashboard/',DashboardView,name='dashboard'),
    path('profile/',ProfileView,name='profile'),
    path('profileupdate/',ProfileUpdateView,name='profileupdate'),


    ################### House OWner Part #######################
    path('rent-list',RentListView,name='rentlist'),
    path('add-rent',AddRentView,name='addrent'),
    path('edit-rent/<int:id>',RentEditView,name='editrent'),
    path('delete-rent/<int:id>',RentDeleteView,name='rentdelete'),

    path('rented-list',RentedListView,name='rentedlist'),
    path('rented-details/<int:id>',RentedListDetailsView,name='renteddetails'),

    ################### Renter Part #######################
    path('pending-rent-list',PendingRentListView,name='pendingrentlist'),
    path('pending-rent-view/<int:id>',PendingRentPreviewiew,name='pendingrentpreview'),
    path('pending-rent-approved/<int:id>',ApprovePendingRentListView,name='approvependingrent'),
    path('pending-rent-cancel/<int:id>',CancelPendingRentListView,name='cancelpendingrent'),

    path('purchase-list',PurchaseListView,name='purchaselist'),
    path('purchase-details/<int:id>',PurchaseDetailsView,name='purchasedetails'),

    ################### Admin #######################
    path('purchase-report',PurchaseReportListView,name='purchasereport'),
    path('report-view',ReportView,name='reportview'),
    path('report-user',UserReportView,name='userreport'),
    path('report-user-view',UserWiseReportView,name='userwisereport'),
    path('contact',ContactMessage,name='contact'),
    path('userlists',UserListView,name='userlists'),
    path('user-active/<int:id>',UserActiveView,name='useractive'),
]

HouseRental/urls.py
from django.contrib import admin
from django.urls import path,include
from HouseRental.views import *
from HouseRental.views import page_not_found
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('post',RentPost,name='post'),
    path('contact',ContactView,name='contact'),
    path('faq',FaqView,name='faq'),
    path('about',AboutView,name='about'),
    path('details/<int:id>',Details,name="details"),
    path('checkout/<int:id>',create_checkout_session,name="checkout"),
    path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('reset-password/',
         PasswordResetView.as_view(template_name='App_Account/password_reset_form.html'), name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='App_Account/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='App_Account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='App_Account/password_reset_complete.html'),
         name='password_reset_complete'),
    path('account/',include('App_Account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# handler404 = page_not_found

templates/App_Admin/pendingpreview.html
{% extends 'App_Dashboard/base.html'%}
{% block title %}
EasyRent-Add rent post
{% endblock %}
{% block css %}
<style>
    .update-container {
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }

    .btnR {
        position: absolute;
        top: 0;
        left: -8px;
    }
</style>
{% endblock %}
{% load static%}
{% block dashboard%}

{% include 'alert.html'%}

<div class="container">
    <div class="row">
        <div class="col-lg-8 mx-auto update-container">
            <div class="main-body">
                <h3 class="text-left border-bottom mb-2">View Rent Post</h2>
                    <div class="g-3" id="AddRentPost">
                        <div class="col-lg-12">
                            <h4>Title : {{house.title}}</h4>
                            <ul>
                                <li>City : {{cities.0.name}} </li>
                                <li>Type : {{house_types.0.label}} </li>
                                <li>House Name : {{house.house_name}} </li>
                                <li>Total Area : {{house.house_area}} </li>
                                <li>Parking : {% if house.is_parking %} Yes {% else %} No {% endif %}</li>
                                <li>Floor No : {{house.floor_no}} </li>
                                <li>Bed Rooms : {{house.total_bedrooms}} </li>
                                <li>Bath Rooms : {{house.total_bathrooms}} </li>
                                <li>Address : {{house.address}} </li>
                                <li>Monthly Rent : {{house.monthly_rent}} </li>
                                <li>Advance Amount : {{house.advacne_rent}} </li>
                            </ul>
                        </div>
                        <div class="col-lg-12">
                            <h5>Map Preview : </h5>
                            {{house.map_link|safe}}
                        </div>
                        <div class="col-lg-12">
                            <h5>Description : </h5>
                            {{ house.description |safe}}
                        </div>
                        <div class="row my-2">
                            <div class="col-lg-12">
                                <h5>Images : </h5>
                                <div class="img-container d-flex" id="imagePreviews">
                                    {% for image in house.images.all %}
                                    <div class="position-relative"><img src="{{ image.image.url }}"
                                            style="width: 200px; height: 200px; margin-right: 10px; margin-bottom: 10px;">
                                    </div>
                                    {% endfor %}
                                </div>

                            </div>
                        </div>
                        </form>


                    </div>
            </div>
        </div>

    </div>

    {% endblock %}
    {% block js%}
    <script>
        const photoInput = document.getElementById('txtImages');
        photoInput.addEventListener('change', previewImages);

        function previewImages() {
            var previewContainer = document.getElementById('imagePreviews');
            var files = document.getElementById('txtImages').files;
            previewContainer.innerHTML = '';

            for (var i = 0; i < files.length; i++) {
                var file = files[i];
                var reader = new FileReader();

                reader.onload = function (e) {
                    var image = document.createElement('img');
                    image.src = e.target.result;
                    image.style.width = '120px';
                    image.style.height = '120px';
                    image.style.marginRight = '10px';
                    image.style.marginBottom = '10px';

                    var deleteBtn = document.createElement('button');
                    deleteBtn.innerHTML = 'x';
                    deleteBtn.classList.add('btn', 'btn-danger', 'btn-sm', 'btnR');
                    deleteBtn.addEventListener('click', function () {
                        previewContainer.removeChild(div);
                    });
                    var div = document.createElement('div');
                    div.appendChild(image);
                    div.appendChild(deleteBtn);
                    div.classList.add('position-relative');

                    previewContainer.appendChild(div);
                }

                reader.readAsDataURL(file);
            }
        }
        $(document).ready(function () {
            $('#AddRentPost').submit(function (event) {
                event.preventDefault();
                var txtImages = document.getElementById('txtImages');
                var txtTitle = $('#txtTitle').val();
                var txtCity = $('#txtCity option:selected').val();
                var txtType = $('#txtType option:selected').val();
                var txtBuilding = $('#txtBuilding').val();
                var txtBedroom = $('#txtBedroom').val();
                var txtBath = $('#txtBath').val();
                var txtArea = $('#txtArea').val();
                var txtParking = $("input[name='txtParking']:checked").val()
                var txtFloor = $('#txtFloor').val();
                var txtMonthlyRent = $('#txtMonthlyRent').val();
                var txtAdvance = $('#txtAdvance').val();
                var txtAddress = $('#txtAddress').val();
                var txtMapUrl = $('#txtMapUrl').val();
                if (txtTitle == "") {
                    $.alert.open('error', 'Enter a rent title.');
                    return false;
                }
                if (txtCity == "0") {
                    $.alert.open('error', 'Select city');
                    return false;
                }
                if (txtType == "0") {
                    $.alert.open('error', 'Select rent type');
                    return false;
                }
                if (txtBuilding == "") {
                    $.alert.open('error', 'Enter a building name.');
                    return false;
                }
                if (txtArea == "") {
                    $.alert.open('error', 'Enter a total area un aquare feet.');
                    return false;
                }
                if (txtParking == undefined) {
                    $.alert.open('error', 'Select parking status.');
                    return false;
                }
                if (txtFloor == "") {
                    $.alert.open('error', 'Enter Floor no.');
                    return false;
                }
                if (txtBedroom == "") {
                    $.alert.open('error', 'Enter no of bed rooms.');
                    return false;
                }
                if (txtBath == "") {
                    $.alert.open('error', 'Enter no of bath rooms.');
                    return false;
                }
                if (txtAddress == "") {
                    $.alert.open('error', 'Enter address.');
                    return false;
                }
                if (txtMapUrl == "") {
                    $.alert.open('error', 'Enter map url.');
                    return false;
                }
                if (txtMonthlyRent == "") {
                    $.alert.open('error', 'Enter Montly rent amount.');
                    return false;
                }
                if (txtAdvance == "") {
                    $.alert.open('error', 'Enter advance amount.');
                    return false;
                }

                $(this).unbind('submit').submit();
            });
        });
    </script>
    {% endblock%}

templates/App_Admin/pendingrentlist.html
{% extends 'App_Dashboard/base.html'%}
{% load static%}
{% block title %}EasyRent - Pending rent list{% endblock %}
{% block dashboard%}
{% block css %}
<link href="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.css" rel="stylesheet">
<style>
    .dataTable {
        width: 100% !important;
    }
</style>
{% endblock %}
{% include 'alert.html'%}
<div class="container-fluid px-4">
    <div class="row my-5">
        <div class="col-lg-12 mb-2">
            <span class="mb-3" style="font-size: 24px;">Pending Rent List</span>
        </div>
        <hr>
        <div class="col">
            <table class="table bg-white rounded shadow-sm  table-hover" id="rentlist">
                <thead>
                    <tr>
                        <th scope="col" width="50">SL</th>
                        <th scope="col">Rent Title</th>
                        <th scope="col">City</th>
                        <th scope="col">Advannce</th>
                        <th scope="col">Total Rent</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in myrent_list%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{item.title}}</td>
                        <td>{{item.city}}</td>
                        <td>{{item.advacne_rent}}</td>
                        <td>{{item.monthly_rent}}</td>
                        <td>{% if item.is_active == True %} <span
                                class="badge bg-success text-light p-2">Approved</span>
                            {% else %}
                            {% if item.is_reject == True%}
                            <span class="badge bg-danger text-light p-2">Cancel</span>
                            {% else %}
                            <span class="badge bg-warning text-light p-2">Pending</span>
                            {% endif %}
                            {% endif %}
                        </td>
                        <td>
                            <div class="d-flex align-items-center list-action">
                                <a class="badge bg-success mx-2"
                                    href="{% url 'App_Account:pendingrentpreview' item.id %}"><i
                                        class="fas fa-eye"></i></a>
                                {% if item.is_rented == False %}
                                {% if item.is_active == False %}
                                <a class="badge bg-success mx-2 btnApprove"
                                    href="{% url 'App_Account:approvependingrent' item.id %}"><i
                                        class="fas fa-check"></i></a>
                                {% endif%}
                                {% if item.is_active == True %}
                                {% if item.is_reject == False %}
                                <a class="badge bg-danger btnReject"
                                    href="{% url 'App_Account:cancelpendingrent' item.id %}">X</a>
                                {% endif%}
                                {% endif%}
                                {% endif%}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}
{% block js%}
<script src="https://cdn.datatables.net/v/dt/dt-2.0.3/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#rentlist').DataTable();
        $(document).on('click', '.btnApprove', function (event) {
            event.preventDefault();
            var url = $(this).attr('href');

            $.alert.open('warning', 'Are you sure you want to approve this post?', function (confirmed) {
                if (confirmed) {
                    window.location.href = url;
                }
            });
        })
        $(document).on('click', '.btnReject', function (event) {
            event.preventDefault();
            var url = $(this).attr('href');

            $.alert.open('warning', 'Are you sure you want to cancel this post?', function (confirmed) {
                if (confirmed) {
                    window.location.href = url;
                }
            });
        })
    });
</script>
{% endblock%}