App_Account/urls.py
from django.urls import path
from App_Account.views import (
    SignupView, LoginView,activateView,DashboardView,LogoutView,PasswordChange,ProfileView,
    ProfileUpdateView,RentListView,AddRentView,RentEditView,RentDeleteView,PendingRentListView,
    PendingRentPreviewiew,ApprovePendingRentListView,CancelPendingRentListView,RentedListView,
    RentedListDetailsView,PurchaseListView,PurchaseDetailsView,PurchaseReportListView,ReportView,
    UserReportView,UserWiseReportView,ContactMessage,UserListView,UserActiveView
    )

app_name = 'App_Account'

urlpatterns = [
    path('signup/', SignupView, name='signup'),
    path('login/', LoginView, name='login'),
    path('logout',LogoutView,name='logout'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',activateView, name='activate'),
    path('password-change/',PasswordChange,name="passwordchange"),
    path('dashboard/',DashboardView,name='dashboard'),
    path('profile/',ProfileView,name='profile'),
    path('profileupdate/',ProfileUpdateView,name='profileupdate'),


    ################### House OWner Part #######################
    path('rent-list',RentListView,name='rentlist'),
    path('add-rent',AddRentView,name='addrent'),
    path('edit-rent/<int:id>',RentEditView,name='editrent'),
    path('delete-rent/<int:id>',RentDeleteView,name='rentdelete'),

    path('rented-list',RentedListView,name='rentedlist'),
    path('rented-details/<int:id>',RentedListDetailsView,name='renteddetails'),

    ################### Renter Part #######################
    path('pending-rent-list',PendingRentListView,name='pendingrentlist'),
    path('pending-rent-view/<int:id>',PendingRentPreviewiew,name='pendingrentpreview'),
    path('pending-rent-approved/<int:id>',ApprovePendingRentListView,name='approvependingrent'),
    path('pending-rent-cancel/<int:id>',CancelPendingRentListView,name='cancelpendingrent'),

    path('purchase-list',PurchaseListView,name='purchaselist'),
    path('purchase-details/<int:id>',PurchaseDetailsView,name='purchasedetails'),

    ################### Admin #######################
    path('purchase-report',PurchaseReportListView,name='purchasereport'),
    path('report-view',ReportView,name='reportview'),
    path('report-user',UserReportView,name='userreport'),
    path('report-user-view',UserWiseReportView,name='userwisereport'),
    path('contact',ContactMessage,name='contact'),
    path('userlists',UserListView,name='userlists'),
    path('user-active/<int:id>',UserActiveView,name='useractive'),
]

HouseRental/urls.py
from django.contrib import admin
from django.urls import path,include
from HouseRental.views import *
from HouseRental.views import page_not_found
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('post',RentPost,name='post'),
    path('contact',ContactView,name='contact'),
    path('faq',FaqView,name='faq'),
    path('about',AboutView,name='about'),
    path('details/<int:id>',Details,name="details"),
    path('checkout/<int:id>',create_checkout_session,name="checkout"),
    path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('reset-password/',
         PasswordResetView.as_view(template_name='App_Account/password_reset_form.html'), name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='App_Account/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='App_Account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='App_Account/password_reset_complete.html'),
         name='password_reset_complete'),
    path('account/',include('App_Account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# handler404 = page_not_found

templates/about.html
{% extends 'base.html'%}
{% load static%}
{% block title %}
Easyrent-Contact Page
{% endblock %}
{% block css %}
<link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/abouts/about-4/assets/css/about-4.css">
{% endblock %}
{% block main %}
{% include 'alert.html'%}
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-12">
            <!-- About 4 - Bootstrap Brain Component -->
            <section class="py-3 py-md-5 py-xl-8">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-10 col-lg-8">
                            <h3 class="fs-5 mb-2 text-secondary text-uppercase">About</h3>
                            <h2 class="display-5 mb-4">At EasyRent, we're passionate about simplifying the rental management experience for landlords and tenants alike.</h2>
                            <button type="button" class="btn btn-lg btn-primary mb-3 mb-md-4 mb-xl-5">Connect Now</button>
                        </div>
                    </div>
                </div>

                <div class="container">
                    <div class="row gy-3 gy-md-4 gy-lg-0">
                        <div class="col-12 col-lg-6">
                            <div class="card bg-light p-3 m-0">
                                <div class="row gy-3 gy-md-0 align-items-md-center">
                                    <div class="col-md-5">
                                        <img src="https://bootstrapbrain.com/demo/components/abouts/about-4/assets/img/about-img-2.jpg"
                                            class="img-fluid rounded-start" alt="Why Choose Us?">
                                    </div>
                                    <div class="col-md-7">
                                        <div class="card-body p-0">
                                            <h2 class="card-title h4 mb-3">Why Choose Us?</h2>
                                            <p class="card-text lead">Choose us because we offer innovative rental management technology designed for simplicity and efficiency, ensuring a user-friendly experience for landlords and tenants alike. With comprehensive solutions, exceptional support, and a commitment to transparency, we're trusted by thousands to streamline the rental process.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-lg-6">
                            <div class="card bg-light p-3 m-0">
                                <div class="row gy-3 gy-md-0 align-items-md-center">
                                    <div class="col-md-5">
                                        <img src="https://bootstrapbrain.com/demo/components/abouts/about-4/assets/img/about-img-1.jpg"
                                            class="img-fluid rounded-start" alt="Visionary Team">
                                    </div>
                                    <div class="col-md-7">
                                        <div class="card-body p-0">
                                            <h2 class="card-title h4 mb-3">Visionary Team</h2>
                                            <p class="card-text lead">Our visionary team comprises diverse talents united by a shared commitment to revolutionizing the rental management industry. With deep expertise in real estate, technology, and customer service, we're dedicated to pushing boundaries and pioneering innovative solutions that exceed expectations.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
{% endblock %}
{% block js%}
<script>

</script>
{% endblock%}

templates/accessdenied.html
<!DOCTYPE html>
{% load static%}
<html>

<head>
    <title>Access Denied</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<style>
    body {
        background-color: black;
        color: white;
    }

    h1 {
        color: red;
    }

    h6 {
        color: red;
        text-decoration: underline;
    }
</style>

<body>
    <div class="w3-display-middle">
        <h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
        <hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
        <h3 class="w3-center w3-animate-right">You dont have permission to view this page.</h3>
        <h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
        <h6 class="w3-center w3-animate-zoom"><a href="{% url 'App_Account:dashboard'%}" class="w3-center">Go Back
                Home</a></h6>
    </div>
</body>

</html>

templates/alert.html
{% load static %}
{% if messages %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<style>
    .toast-top-right {
        top: 10%;
    }
</style>
{% for message in messages %}
<script>
    $(document).ready(function () {
        {% if message.tags == 'success' %}
        toastr.success("{{ message }}");
        {% elif message.tags == 'error' %}
        toastr.error("{{ message }}");
        {% else %}
        toastr.error("{{ message }}");
        {% endif %}
    });
</script>
{% endfor %}
{% endif %}

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title%}EasyRent - Welcome{% endblock%}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href="{% static 'img/favicon.ico'%}" rel="icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap"
        rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    <link href="{% static 'alert/css/alert.css'%}" rel="stylesheet" />
    <link href="{% static 'alert/themes/default/theme.css'%}" rel="stylesheet" />
    {% block css %}
    {% endblock %}                        
</head>
     
<body>
    <div class="container-xxl bg-white p-0">
        <!-- Header Start -->
        <div class="container-fluid bg-dark px-0">
            <div class="row gx-0">
                <div class="col-lg-3 bg-dark d-none d-lg-block">
                    <a href="{% url 'home' %}"
                        class="navbar-brand w-100 h-100 m-0 p-0 d-flex align-items-center justify-content-center">
                        <h1 class="m-0 text-primary text-uppercase">EasyRent</h1>
                    </a>
                </div>
                <div class="col-lg-9">
                    <nav class="navbar navbar-expand-lg bg-dark navbar-dark p-3 p-lg-0">
                        <a href="{% url 'home' %}" class="navbar-brand d-block d-lg-none">
                            <h1 class="m-0 text-primary text-uppercase">EasyRent</h1>
                        </a>
                        <button type="button" class="navbar-toggler" data-bs-toggle="collapse"
                            data-bs-target="#navbarCollapse">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                            <div class="navbar-nav mr-auto py-0">
                                <a href="{% url 'home' %}" class="nav-item nav-link">Home</a>
                                <a href="{% url 'post' %}" class="nav-item nav-link">Post</a>
                                <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                                <a href="{% url 'contact'%}" class="nav-item nav-link">Contact</a>
                                <a href="{% url 'faq' %}" class="nav-item nav-link">Faq</a>
                            </div>
                            <div class="navbar-nav">
                                {% if user.is_authenticated %}
                                <a href="{% url 'App_Account:dashboard'%}" class="nav-item nav-link">welcome
                                    {{request.user}}</a>
                                <a href="{% url 'App_Account:logout'%}" class="nav-item nav-link">Logout</a>
                                {% else %}
                                <a href="{% url 'App_Account:signup'%}" class="nav-item nav-link">Signup</a>
                                <a href="{% url 'App_Account:login'%}" class="nav-item nav-link">Login</a>
                                {% endif %}
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Header End -->
        {% block main%}

        {% endblock%}

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer">
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-12 text-center mb-3 mb-md-0">
                            &copy;EasyRent, All Right Reserved.
                            Designed By Alex</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    <!--Start of Tawk.to Script-->
    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/661e54f11ec1082f04e2f951/1hrj7nk7r';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->
    <!--End of Tawk.to Script-->
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
    <script src="{% static 'alert/js/alert.js'%}"></script>
    <script>
        $(document).ready(function (event) {
            $(".scope-reply-btn").click(function () {
                $(this).parent().parent().next(".scope-replied-comments").fadeToggle();
            });

            $(document).on("submit", ".scope-comment-form", function (event) {
                console.log("scope comment");
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: $(this).attr("action"),
                    data: $(this).serialize(),
                    dataType: "json",
                    success: function (response) {
                        $(".scope-comment-section").html(response["form"]);
                        $("textarea").val("");
                        $(".scope-reply-btn").click(function () {
                            $(this)
                                .parent()
                                .parent()
                                .next(".scope-replied-comments")
                                .fadeToggle();
                        });
                        $("textarea").val("");
                    },
                    error: function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
            $(document).on("submit", ".scope-reply-form", function (event) {
                console.log("ok");
                event.preventDefault();
                $.ajax({
                    type: "POST",
                    url: $(this).attr("action"),
                    data: $(this).serialize(),
                    dataType: "json",
                    success: function (response) {
                        $(".scope-comment-section").html(response["form"]);
                        $("textarea").val("");
                        $(".scope-reply-btn").click(function () {
                            $(this)
                                .parent()
                                .parent()
                                .next(".scope-replied-comments")
                                .fadeToggle();
                        });
                        $("textarea").val("");
                    },
                    error: function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });

        })

    </script>
    {% block js %}

    {% endblock %}
</body>

</html>

templates/comment_section.html
<!-- 
<h4 class="p-title mt-20"><b>{{ comments.count }} COMMENTS</b></h4>
<div style="max-height: 1000px;overflow: auto;">
    {% for comment in comments %}

        <div class="event-replied-comments container mt-2 ml-40" style="display: none">
            {% for reply in comment.replies.all %}
            <blockquote class="blockquote">
                <p class="mb-0" style="color: #0000cc;font-size: 15px;">{{ reply.content }}</p>
                <footer class="blockquote-footer">

                    by
                    <img src="{{ reply.user.regularuser.photo.url }}" width="25px" height="25px" class="comment-img">
                    <cite title="Source Title" style="color: #29b323">{{ reply.user|capfirst }}</cite>
                    <code>{{ reply.timestamp }}</code>

                </footer>
            </blockquote>
            {% endfor %}

            <div class="form-group row ml-60 ">
                <form class="event-reply-form form-block form-plr-15 form-h-45 form-mb-20 form-brdr-lite-white mb-md-50"
                    action="{% url 'details' rent.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {{ comment_form }}
                    <button class="btn btn-primary mt-2" type="submit"><b>LEAVE A REPLY</b></button>
                </form>

            </div>

        </div>

        {% endfor %}
    </div> -->


<h3>Comment </h3>
<form class="scope-comment-form" action="{% url 'details' rent.id %}" method="post">{% csrf_token %}
    {{ comment_form }}
    <button class="btn btn-primary mt-1" type="submit"><b>COMMENT</b></button>
</form>


<h4 class="p-title mt-20" style="margin-top: 2%;"><b>{{ comments.count }} COMMENTS</b></h4>
<div style="max-height: 1200px;overflow: auto;">
    {% for comment in comments %}
    <div class="blockquote">
        <p class="mb-0" style="font-size: 14px;">{{ comment.content }}</p>
        <footer class="blockquote-footer mt-2">by
            <img src="{{ comment.user.userprofile.photo.url }}" width="25px" height="25px" class="comment-img">
            <span title="Source Title mx-4" style="color: red;margin-right: 10px;">
                {{comment.user|capfirst}}</span><code>{{ comment.timestamp }}</code>
            <button type="submit" class="scope-reply-btn btn btn-outline-dark btn-sm">Reply</button>
        </footer>
    </div>
    <div class="scope-replied-comments container mt-2 ml-40" style="display: none;padding: 2% 4%;">
        {% for reply in comment.replies.all %}
        <div class="blockquote">
            <p class="mb-0" style="font-size: 14px;">{{ reply.content }}</p>
            <footer class="blockquote-footer mt-2">
                by
                <img src="{{ reply.user.userprofile.photo.url }}" width="25px" height="25px" class="comment-img">
                <cite class="mx-2" title="Source Title" style="color: #29b323">{{ reply.user|capfirst }}</cite>
                <code>{{ reply.timestamp }}</code>

            </footer>
            </blockquote>
            {% endfor %}
            <div class="form-group row ml-60 ">
                <form class="scope-reply-form" action="{% url 'details' rent.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    {{ comment_form }}
                    <button class="btn btn-success my-2" style="margin-top: 2%;" type="submit"><b>REPLY</b></button>
                </form>

            </div>

        </div>

        {% endfor %}
    </div>

templates/contact.html
{% extends 'base.html'%}
{% load static%}
{% block title %}
Easyrent-Contact Page
{% endblock %}
{% block css %}
<style>
    .update-container {
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }
</style>
{% endblock %}
{% block main %}
{% include 'alert.html'%}
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-12">

            <div class="col-sm-6 mx-auto update-container">
                <div class="contact_1">
                    <h2 class="text-center">CONTACT US</h2>
                </div>
                <form method="post">{% csrf_token %}
                    <div class="contact_2">

                        <input type="text" class="form-control my-2" name="name" placeholder="Name"
                            pattern="[a-zA-Z0-9 a-zA-Z0-9]+" minlength="4" maxlength="20" required>
                        <input type="text" class="form-control my-2" name="email" placeholder="example@gmail.com"
                            pattern=".+@gmail\.com" required>
                        <textarea placeholder="Message" name="about" class="form-control my-2" minlength="10"
                            required></textarea>
                    </div>
                    <input type="submit" class="btn btn-primary w-100" value="SEND">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/faq.html
{% extends 'base.html'%}
{% load static%}
{% block title %}
Easyrent-Contact Page
{% endblock %}
{% block css %}
<style>
    .accordion-item {
        background-color: #FFFFFF;
        border: 1px solid #E0E0E0;
        border-radius: 8px;
        margin-bottom: 10px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .accordion-header {
        background-color: #fea116;
        color: #FFFFFF;
        padding: 15px;
        font-size: 18px;
        border: none;
        width: 100%;
        text-align: left;
        cursor: pointer;
        outline: none;
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-radius: 8px 8px 0 0;
        transition: background-color 0.3s ease;
    }

    .accordion-header:hover {
        background-color: #000000;
    }

    .accordion-content {
        background-color: #FAFAFA;
        /* Very light grey for content */
        overflow: hidden;
        padding: 0 15px;
        max-height: 0;
        transition: max-height 0.3s ease;
    }

    .accordion-content p {
        margin: 15px 0;
        line-height: 1.5;
    }

    .icon {
        transition: transform 0.3s ease;
    }

    .active .icon {
        transform: rotate(45deg);
    }

    .footer {
        position: fixed;
        bottom: 0;
    }
</style>
{% endblock %}
{% block main %}
{% include 'alert.html'%}
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-12">
            <div class="accordion-container">
                <h2 class="text-center">Frequently Asked Questions</h2>
                <div class="accordion-item">
                    <button class="accordion-header">
                        How does EasyRent work?<span class="icon">+</span>
                    </button>
                    <div class="accordion-content">
                        <p>Our platform provides House-Owners with tools to manage their rental properties online, including listing creation, renter screening, lease management, and maintenance tracking. Tenants can easily search for available properties, submit rental applications, and communicate with house-owners through our platform. Our goal is to make the entire rental process seamless and convenient for both House-Owners and Renters.</p>
                    </div>
                </div>
                <div class="accordion-item">
                    <button class="accordion-header">
                        What sets EasyRent apart from other rental management platforms? <span class="icon">+</span>
                    </button>
                    <div class="accordion-content">
                        <p>EasyRent stands out for its user-friendly interface, comprehensive features, exceptional support, and commitment to transparency. Our platform is designed to be intuitive and easy to use, even for users with little to no technical experience. We offer a wide range of features to meet all your rental management needs, backed by a dedicated support team that's always ready to assist you. Plus, we believe in being transparent with our pricing, terms, and policies, so you know exactly what to expect when you choose us.</p>
                    </div>
                </div>
                <div class="accordion-item">
                    <button class="accordion-header">
                        Is EasyRent suitable for landlords with multiple properties? <span class="icon">+</span>
                    </button>
                    <div class="accordion-content">
                        <p>Absolutely! EasyRent is perfect for house-owners with multiple properties. Our platform allows you to manage all your properties from one centralized dashboard, making it easy to stay organized and efficient. Whether you have one property or one hundred, our platform can scale to meet your needs.</p>
                    </div>
                </div>
                <div class="accordion-item">
                    <button class="accordion-header">
                        How secure is EasyRent? <span class="icon">+</span>
                    </button>
                    <div class="accordion-content">
                        <p>We take the security of your data seriously. Our platform employs robust security measures to protect your information, including encryption, firewalls, and regular security audits. Additionally, we adhere to industry best practices and comply with all relevant data protection regulations to ensure your data remains safe and secure at all times.</p>
                    </div>
                </div>
                <div class="accordion-item">
                    <button class="accordion-header">
                        How can I get started with EasyRent? <span class="icon">+</span>
                    </button>
                    <div class="accordion-content">
                        <p>Getting started with EasyRent is easy! Simply sign up for an account on our website, and you'll gain instant access to our platform. From there, you can start listing your properties, screening renters, and managing your rentals online. If you have any questions or need assistance, our support team is here to help you every step of the way.
                        </p>
                    </div>
                </div>

                <div class="accordion-item">
                    <button class="accordion-header">
                        What if I have additional questions or need support? <span class="icon">+</span>
                    </button>
                    <div class="accordion-content">
                        <p>If you have any additional questions or need support, don't hesitate to contact our friendly support team. You can reach us by phone, email, or through our website, and we'll be happy to assist you with any inquiries or issues you may have.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js%}
<script>
    document.querySelectorAll('.accordion-header').forEach(button => {
        button.addEventListener('click', () => {
            const accordionContent = button.nextElementSibling;

            button.classList.toggle('active');

            if (button.classList.contains('active')) {
                accordionContent.style.maxHeight = accordionContent.scrollHeight + 'px';
            } else {
                accordionContent.style.maxHeight = 0;
            }

            // Close other open accordion items
            document.querySelectorAll('.accordion-header').forEach(otherButton => {
                if (otherButton !== button) {
                    otherButton.classList.remove('active');
                    otherButton.nextElementSibling.style.maxHeight = 0;
                }
            });
        });
    });

</script>
{% endblock%}

templates/orderconfirmation.html
{% autoescape off %}
Hi {{ user.username }}.
You have successfully payment for a rental post.which title is "{{house.title}}" and your order no id {{order.id}},
paid
${{house.advacne_rent}}.
Thanks for using EasyRent.
{% endautoescape %}

templates/success.html
{% extends 'base.html'%}
{% block css%}
<style>
    .footer {
        position: fixed;
        bottom: 0;
    }
</style>
{% endblock%}

{% block main%}
<div class="container bg-success" style="margin-top:5%;margin-bottom: 5%;">
    <div class="row">
        <div class="jumbotron p-4" style="box-shadow: 2px 2px 4px #000000;">
            <h2 class="text-center text-primary">YOUR ORDER HAS BEEN RECEIVED</h2>
            <h4 class="text-center text-primary">Thank you for your payment, it’s processing</h3>

                <p class="text-center text-white">Your order # is: {{order.id}}</p>
                <p class="text-center text-white">You will receive an order confirmation email with details of your
                    order and a
                    link to
                    track your process.</p>
                <center>
                    <div class="btn-group" style="margin-top:50px;">
                        <a href="{% url 'details' order.post.id %}" class="btn btn-lg btn-warning">CONTINUE</a>
                    </div>
                </center>
        </div>
    </div>
</div>
{% endblock %}