App_Account/urls.py
from django.urls import path
from App_Account.views import (
    SignupView, LoginView,activateView,DashboardView,LogoutView,PasswordChange,ProfileView,
    ProfileUpdateView,RentListView,AddRentView,RentEditView,RentDeleteView,PendingRentListView,
    PendingRentPreviewiew,ApprovePendingRentListView,CancelPendingRentListView,RentedListView,
    RentedListDetailsView,PurchaseListView,PurchaseDetailsView,PurchaseReportListView,ReportView,
    UserReportView,UserWiseReportView,ContactMessage,UserListView,UserActiveView
    )

app_name = 'App_Account'

urlpatterns = [
    path('signup/', SignupView, name='signup'),
    path('login/', LoginView, name='login'),
    path('logout',LogoutView,name='logout'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',activateView, name='activate'),
    path('password-change/',PasswordChange,name="passwordchange"),
    path('dashboard/',DashboardView,name='dashboard'),
    path('profile/',ProfileView,name='profile'),
    path('profileupdate/',ProfileUpdateView,name='profileupdate'),


    ################### House OWner Part #######################
    path('rent-list',RentListView,name='rentlist'),
    path('add-rent',AddRentView,name='addrent'),
    path('edit-rent/<int:id>',RentEditView,name='editrent'),
    path('delete-rent/<int:id>',RentDeleteView,name='rentdelete'),

    path('rented-list',RentedListView,name='rentedlist'),
    path('rented-details/<int:id>',RentedListDetailsView,name='renteddetails'),

    ################### Renter Part #######################
    path('pending-rent-list',PendingRentListView,name='pendingrentlist'),
    path('pending-rent-view/<int:id>',PendingRentPreviewiew,name='pendingrentpreview'),
    path('pending-rent-approved/<int:id>',ApprovePendingRentListView,name='approvependingrent'),
    path('pending-rent-cancel/<int:id>',CancelPendingRentListView,name='cancelpendingrent'),

    path('purchase-list',PurchaseListView,name='purchaselist'),
    path('purchase-details/<int:id>',PurchaseDetailsView,name='purchasedetails'),

    ################### Admin #######################
    path('purchase-report',PurchaseReportListView,name='purchasereport'),
    path('report-view',ReportView,name='reportview'),
    path('report-user',UserReportView,name='userreport'),
    path('report-user-view',UserWiseReportView,name='userwisereport'),
    path('contact',ContactMessage,name='contact'),
    path('userlists',UserListView,name='userlists'),
    path('user-active/<int:id>',UserActiveView,name='useractive'),
]

HouseRental/urls.py
from django.contrib import admin
from django.urls import path,include
from HouseRental.views import *
from HouseRental.views import page_not_found
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name='home'),
    path('post',RentPost,name='post'),
    path('contact',ContactView,name='contact'),
    path('faq',FaqView,name='faq'),
    path('about',AboutView,name='about'),
    path('details/<int:id>',Details,name="details"),
    path('checkout/<int:id>',create_checkout_session,name="checkout"),
    path('success/', success, name='success'),
    path('cancel/', cancel, name='cancel'),
    path('reset-password/',
         PasswordResetView.as_view(template_name='App_Account/password_reset_form.html'), name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='App_Account/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='App_Account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='App_Account/password_reset_complete.html'),
         name='password_reset_complete'),
    path('account/',include('App_Account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# handler404 = page_not_found

App_Account/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App_Account.models import UserProfile, USER_TYPE_LIST

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=30, required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.',widget=forms.EmailInput(attrs={'class': 'form-control'}))
    user_type = forms.ChoiceField(choices=USER_TYPE_LIST,required=True,widget=forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'user_type')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'password1':
                field.widget.attrs.update({'class': 'form-control', 'placeholder': 'Enter Password'})
            elif field_name == 'password2':
                field.widget.attrs.update({'class': 'form-control', 'placeholder': 'Confirm Password'})
            elif isinstance(field.widget, forms.Select):  # Check if the widget is a Select widget
                field.widget.attrs.update({'class': 'form-control form-select',  'required': 'required','placeholder':  field_name.replace('_', ' ').capitalize()})
            else:
                field.widget.attrs.update({'class': 'form-control',  'required': 'required','placeholder': field_name.replace('_', ' ').capitalize()})
    
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken. Please choose a different one.")
        return username
    
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")
        user_type = cleaned_data.get("user_type")
        if user_type == '0':
            self.add_error('user_type', 'Please select a user type.')
        return cleaned_data

App_Account/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages,auth
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout, login as auth_login, authenticate,update_session_auth_hash
import requests
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse
from functools import wraps
from App_Rental.models import City,House,HouseImage,HOUSE_TYPE_LIST,HouseRent,ContractUs
from App_Rental.forms import HouseForm
from django.shortcuts import get_object_or_404
from datetime import date
from App_Account.models import *
from django.core.files.storage import FileSystemStorage


def house_owner_required(view_func):
    @wraps(view_func)
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.userprofile.userType == "1":
                return view_func(request, *args, **kwargs)
            else:
                return render(request, 'accessdenied.html')
        else:
            return redirect('App_Account:login')
    return wrapper

def renter_required(view_func):
    @wraps(view_func)
    def wrapper(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.userprofile.userType == "2":
            return view_func(request, *args, **kwargs)
        else:
            return render(request, 'accessdenied.html')
    return wrapper

def admin_required(view_func):
    @wraps(view_func)
    def wrapper(request, *args, **kwargs):
        if not request.user.is_superuser:
            return render(request,'accessdenied.html')
        return view_func(request, *args, **kwargs)
    return wrapper


def SignupView(request):
    if request.method == 'POST':
        username        = request.POST['username']
        email           = request.POST['email']
        password        = request.POST['password']
        confirmPassword = request.POST['confirmPassword']
        userType        = request.POST['userType']
        if User.objects.filter(username=username).exists():
            messages.error(request,"Username already exists.")
        elif User.objects.filter(email=email).exists():
            messages.error(request,"Email already exists.")    
        elif password!=confirmPassword:
            messages.error(request,"Password not matching.")
        elif userType=="0":
            messages.error(request,"User type not selected.")
        else:
            user=User.objects.create_user(username=username,email=email,password=password)
            user.is_active = False
            user.save()
            user.refresh_from_db()
            #User Activation
            current_site=get_current_site(request)
            user.userprofile.userType=userType
            user.save()
            user.refresh_from_db()
            mail_subject='EasyRent Account Activation'
            message=render_to_string('App_Account/account_verification_email.html',{
                'user': user,
                'domain': current_site,
                'uid':  urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request,"Registrations successfull")
            return redirect('/account/login?command=verification&email='+str(to_email))
        return render(request, 'App_Account/signup.html') 
    return render(request,'App_Account/signup.html')

def LoginView(request):
    auth.logout(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            auth_login(request, user)
            # messages.success(request,"you are now authenticated")
            url=request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query 
                params=dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:   
                return redirect('home')
        else:
            messages.error(request, "invalid credential")
            return redirect('App_Account:login')
    context={}
    return render(request,'App_Account/login.html',context)

@login_required(login_url='login')
def logout(request):
    auth.logout(request)
    messages.success(request, "Successfully Logout")
    return redirect('App_Account:login')


def activateView(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
        
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request,'Email Confiemd.')
        return redirect('App_Account:login')
    else:
        return HttpResponse('Activation link is invalid!')
    

@login_required(login_url='App_Account:login')      
def LogoutView(request):
    auth.logout(request)
    messages.success(request, "Successfully Logout")
    return redirect('App_Account:login')

@login_required(login_url='App_Account:login')  
def PasswordChange(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('App_Account:dashboard')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'App_Account/change_password.html', {
        'form': form
    })

@login_required(login_url='App_Account:login') 
def DashboardView(request):
    houses=House.objects.all()
    users=UserProfile.objects.all()
    rented=HouseRent.objects.filter(is_paid=True)
    total=0
    for i in rented:
        total+=i.post.advacne_rent
    context={
        'housepost':houses.count,
        'approved':houses.filter(is_active=True,is_reject=False).count,
        'rejected':houses.filter(is_reject=True).count,
        'saled':houses.filter(is_rented=True).count,
        'users':users.count,
        'houseowner':users.filter(userType=1).count,
        'renter':users.filter(userType=2).count,
        'totalreneted':total
    }
    return render(request,'App_Dashboard/dashboard.html',context)    

@login_required(login_url='App_Account:login') 
def ProfileView(request):
    return render(request,'App_Dashboard/profile.html')    

@login_required(login_url='App_Account:login') 
def ProfileUpdateView(request):
    profile_instance = request.user.userprofile
    if request.method == 'POST':
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        mobile = request.POST.get('mobile')
        nid = request.POST.get('nid')
        city = request.POST.get('city')
        present_address = request.POST.get('presentAddress')
        permanent_address = request.POST.get('permanentAddress')
        
        request.user.first_name = first_name
        request.user.last_name = last_name
        profile_instance.mobile = mobile
        profile_instance.nid = nid
        profile_instance.city = city
        profile_instance.present_address = present_address
        profile_instance.permanent_address = permanent_address
        
        if 'photo' in request.FILES:
            photo_file = request.FILES['photo']
            profile_instance.photo = photo_file
        request.user.save()
        profile_instance.save()
        messages.success(request,"Profile update successfully.")
        return redirect('App_Account:profile') 
    return render(request,'App_Dashboard/profile_update.html')    

@house_owner_required
def RentListView(request):
    myrent_list=House.objects.filter(owner=request.user)
    context={
        'myrent_list':myrent_list
    }
    return render(request,'App_Dashboard/rentlist.html',context)

@house_owner_required
def RentEditView(request,id):
    house = get_object_or_404(House, id=id)
    if request.method == 'POST':
        txtTitle = request.POST.get('txtTitle')
        txtCity = request.POST.get('txtCity')
        txtType = request.POST.get('txtType')
        txtBuilding = request.POST.get('txtBuilding')
        txtArea = request.POST.get('txtArea')
        txtParking = request.POST.get('txtParking')
        txtFloor = request.POST.get('txtFloor')
        txtBedroom = request.POST.get('txtBedroom')
        txtBath = request.POST.get('txtBath')
        txtAddress = request.POST.get('txtAddress')
        txtMapUrl = request.POST.get('txtMapUrl')
        txtMonthlyRent = request.POST.get('txtMonthlyRent')
        txtAdvance = request.POST.get('txtAdvance')
        txtDescription = request.POST['description']
        rentForm = request.POST.get('txtRentFrom')
        city = City.objects.get(id=txtCity)
        is_parking = True if txtParking == "1" else False  

        house.title = txtTitle
        house.city = city
        house.rent_from=rentForm

templates/App_Account/account_verification_email.html
{% autoescape off %}
Hi {{ user.username }}, Thanks for signup EasyRent.
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'App_Account:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/App_Account/change_password.html
{% extends 'App_Dashboard/base.html' %}
{% load static %}
{% block title %}
Change password
{% endblock %}
{% block css%}
<style>
    .section-conten {
        max-width: 500px;
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }

    .section-conten label {
        width: 100%;
        margin-bottom: 10px;
        font-size: 16px;
        font-weight: 600;
    }

    .section-conten input {
        display: block;
        width: 100%;
        padding: .375rem .75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #666565;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        appearance: none;
        border-radius: 2px;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .errorlist li {
        color: red;
    }
</style>
{% endblock%}
{% block dashboard %}
<section class="section-conten padding-y">
    <h2 class="text-center mb-4">Reset Password</h2>
    <form method="post">{% csrf_token %}
        {{ form }}
        <div class="my-4">
            <button type="submit" class="btn btn-primary w-100">Change Password</button>
        </div>
    </form>
</section>

{% endblock %}

templates/App_Account/forgetpassword.html
{% extends 'App_Dashboard/base.html'%}

{% block dashboard %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">
    <div class="card mx-auto" style="max-width: 500px; margin-top:100px;">
        {% include 'alert.html'%}
        <div class="card-body">
            <h4 class="card-title mb-4">Forget Password</h4>
            <form method="POST" action="{% url 'App_Account:forgetpassword' %}">{% csrf_token %}
                <div class="form-group mb-3">
                    <input type="text" class="form-control" placeholder="Email Address" name="email">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Submit </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->
    <br><br>

</section>
{% endblock %}

templates/App_Account/login.html
{% extends 'base.html'%}
{% load static%}
{% block title%}EasyRent - login{% endblock%}
{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }

    .signup-container {
        max-width: 500px;
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }
</style>
{% endblock %}

{% block main %}
{% if request.GET.command == 'verification' %}
<div class="container mx-auto alert alert-info text-center" role="alert" style="    margin: 50px 0px;">
    Thank you for signup. We have sent you a verification email to your email address {{request.GET.email}}
    <br><br>
    Already verified <a href="{% url 'App_Account:login' %}">Login</a>

</div>
{% else %}
{% include 'alert.html'%}
<div class="signup-container">
    <h2 class="text-center mb-4">Sign In</h2>
    <form method="POST" id="signupForm">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
        <button type="submit" class="btn btn-primary w-100" id="btnSubmit">Sign in</button>
    </form>
    <div class="text-center mt-3">
        Don't have an account? <a href="{% url 'App_Account:signup'%}">Register</a><br>
        Forgot Password? <a href="{% url 'password_reset'%}">Reset Password</a>
    </div>
</div>
{% endif %}
{% endblock%}

{% block js%}
<script>
    $(document).ready(function () {
        $('#signupForm').submit(function (event) {
            event.preventDefault();
            var username = $('#username').val().trim();
            var password = $('#password').val();

            if (username == "") {
                $.alert.open('error', 'Enter username');
                return false;
            }
            if (password == "") {
                $.alert.open('error', 'Enter password.');
                return false;
            }
            $(this).unbind('submit').submit();
        });
    });
</script>
{% endblock%}

templates/App_Account/password_reset_complete.html
{% extends 'base.html'%}
{% load static %}
{% block title%}EasyRent - Reset password complete {% endblock%}
{% block css%}
<style>
        .footer {
                position: fixed;
                bottom: 0;
        }
</style>
{% endblock%}
{% block main %}
<div class="container mx-auto alert alert-info text-center" role="alert" style="    margin: 50px 0px;">
        Your new password has been set. You can log in now on the<br>
        <a class="text-primary" href="{% url 'App_Account:login'%}">Log in</a>
</div>
{% endblock %}

templates/App_Account/password_reset_confirm.html
{% extends 'base.html'%}
{% load static %}
{% block title%}
EasyRent - Reset password confirm
{% endblock %}
{% block css%}
<style>
    .section-conten {
        max-width: 500px;
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }

    .section-conten label {
        width: 100%;
        margin-bottom: 10px;
        font-size: 16px;
        font-weight: 600;
    }

    .section-conten input {
        display: block;
        width: 100%;
        padding: .375rem .75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #666565;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        appearance: none;
        border-radius: 2px;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .errorlist li {
        color: red;
    }
</style>
{% endblock%}
{% block main %}
{% if validlink %}
{% include 'alert.html'%}
<section class="section-conten padding-y">
    <h4 class="text-left mb-4">Change Password</h4>
    <form method="post" class="">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary mt-2 w-100">Change password</button>
    </form>
</section>

{% else %}
<h4 class="col-md-12 text-danger mt-4 text-center">
    The password reset link was invalid, possibly because it has already been used.
    Please request a new password reset.
</h4>
{% endif %}
{% endblock %}

templates/App_Account/password_reset_done.html
{% extends 'base.html'%}
{% load static %}
{% block title%}EasyRent - Reset password done {% endblock%}
{% block css%}
<style>
    .footer {
        position: fixed;
        bottom: 0;
    }
</style>
{% endblock%}
{% block main %}
<div class="container mx-auto alert alert-info text-center" role="alert" style="    margin: 50px 0px;">
    We've emailed you instructions for setting your password. You should receive the email shortly!.
    I takes up to 5 min.
</div>
{% endblock %}

templates/App_Account/password_reset_form.html
{% extends 'base.html'%}
{% load static %}
{% block title%}EasyRent - Reset password{% endblock%}
{% block css %}
<style>
    .section-container {
        max-width: 500px;
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }

    .section-container label {
        width: 100%;
        margin-bottom: 10px;
        font-size: 16px;
        font-weight: 600;
    }

    .section-container input {
        display: block;
        width: 100%;
        padding: .375rem .75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #666565;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        appearance: none;
        border-radius: 2px;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .errorlist li {
        color: red;
    }
</style>
{% endblock %}
{% block main %}
<div class="section-container">
    <p class="text-center mb-4">Enter your email address below, and we'll email instructions for setting a new one.</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary w-100 mt-3">Send me instructions</button>
    </form>
</div>


{% endblock %}

templates/App_Account/signup.html
{% extends 'base.html'%}
{% load static%}
{% block title%}EasyRent - signup{% endblock%}
{% block css %}
<style>
    body {
        background-color: #f8f9fa;
    }

    .signup-container {
        max-width: 500px;
        margin: auto;
        margin-top: 50px;
        margin-bottom: 50px;
        padding: 30px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
    }
</style>
{% endblock %}

{% block main %}
{% include 'alert.html'%}
<div class="signup-container mb-5">
    <h2 class="text-center mb-4">Sign Up</h2>
    <form method="POST" id="signupForm">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
        <div class="mb-3">
            <label for="confirmPassword" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="confirmPassword" name="confirmPassword"
                placeholder="Confirm password">
        </div>
        <div class="mb-3">
            <label for="userType" class="form-label">User Type</label>
            <select class="form-select" name="userType" id="userType">
                <option value="0">Select</option>
                <option value="1">House Owner</option>
                <option value="2">Renter</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary w-100" id="btnSubmit">Sign Up</button>
    </form>
    <div class="text-center mt-3">
        Already have an account? <a href="{% url 'App_Account:login'%}">Login</a>
    </div>
</div>
{% endblock%}

{% block js%}
<script>
    $(document).ready(function () {
        $('#signupForm').submit(function (event) {
            event.preventDefault();
            var username = $('#username').val().trim();
            var email = $('#email').val().trim();
            var password = $('#password').val();
            var confirmPassword = $('#confirmPassword').val();
            var userType = $('#userType option:selected').val();

            if (username == "") {
                $.alert.open('error', 'Enter username');
                return false;
            }
            if (email == "") {
                $.alert.open('error', 'Enter email address.');
                return false;
            } else {
                var emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                if (!emailPattern.test(email)) {
                    $.alert.open('error', 'Please enter a valid email address.');
                    return false;
                }
            }
            if (password.length < 8) {
                $.alert.open('error', 'Enter minimum 8 digit password.');
                return false;
            }

            if (password !== confirmPassword) {
                $.alert.open('error', 'Password not matching');
                return false;
            }
            if (userType == '0') {
                $.alert.open('error', 'Select user type.');
                return false;
            }
            $(this).unbind('submit').submit();
        });
    });
</script>
{% endblock%}